tbl.logs <- read.table("logs.tsv", sep=",", as.is=TRUE, header=TRUE)
tbl.trees <- read.table("trees.tsv", sep=",", as.is=TRUE, header=TRUE,nrow=-1)
tbl.healthyFerns <- read.table("healthyFerns.tsv", sep=",", as.is=TRUE, header=TRUE,nrow=-1)
tbl.deadFerns <- read.table("deadFerns.tsv", sep=",", as.is=TRUE, header=TRUE,nrow=-1)

with(tbl.deadFerns, plot(x,y, xlim=c(-30, 65)))
with(tbl.healthyFerns, points(x,y, col="green", pch=16))
with(tbl.trees, points(x, y, col="lightblue", pch=16, cex=2))
with(tbl.logs, lines(x=c(x[1], x[2]), y=c(y[1], y[2]), lwd=10))
with(tbl.logs, lines(x=c(x[3], x[4]), y=c(y[3], y[4]), lwd=20))
